name: .NET CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -r win-x64 -o publish -p:PublishSingleFile=true -p:SelfContained=true ReadySetTarkov\ReadySetTarkov.csproj
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: ReadySetTarkov
        path: publish/*

